(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
// Generated by CoffeeScript 1.7.1
(function() {
  var Model, View, body, misc, model, view;

  Model = require("./model.coffee");

  View = require("./view.coffee");

  misc = require("./misc.coffee");

  view = void 0;

  model = void 0;

  body = $("body");

  beforeEach(function() {
    model = new Model({
      firstName: "John",
      lastName: "Doe",
      age: 30
    });
    view = new View({
      model: model
    });
    view.render();
    return body.append(view.$el);
  });

  afterEach(function() {
    return view.remove();
  });

  describe("Model", function() {
    it("Should have a firstName property", function() {
      expect(model.get("firstName")).to.exist;
      return expect(model.get("firstName")).to.equal("John");
    });
    it("Should have a lastName property", function() {
      expect(model.get("lastName")).to.exist;
      return expect(model.get("lastName")).to.equal("Doe");
    });
    it("Should have an age property", function() {
      expect(model.get("age")).to.exist;
      return expect(model.get("age")).to.equal(30);
    });
    return it("Should have a working fullName method", function() {
      var fn;
      expect(model.fullName).to.be.a("function");
      fn = model.fullName();
      return expect(fn).to.equal("John Doe");
    });
  });

  describe("View", function() {
    it("Should have a displayContents method", function() {
      return expect(view.displayContents).to.be.a("function");
    });
    it("Should have rendered correctly", function() {
      var td, tr;
      tr = $("tr");
      td = $("td");
      expect(tr.length).to.equal(2);
      return expect(td.length).to.equal(6);
    });
    return it("Should have working events", function() {
      $(".cell.first-name").click();
      expect(window.lastContent).to.equal("John");
      $(".cell.last-name").click();
      expect(window.lastContent).to.equal("Doe");
      $(".cell.age").click();
      return expect(window.lastContent).to.equal("30");
    });
  });

}).call(this);

},{"./misc.coffee":2,"./model.coffee":3,"./view.coffee":4}],2:[function(require,module,exports){
// Generated by CoffeeScript 1.7.1
(function() {
  window.lastContent = "";

  window.displayContents = function(el) {
    return window.lastContent = el.innerHTML;
  };

}).call(this);

},{}],3:[function(require,module,exports){
// Generated by CoffeeScript 1.7.1
(function() {
  var Model,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Model = (function(_super) {
    __extends(Model, _super);

    function Model() {
      return Model.__super__.constructor.apply(this, arguments);
    }

    Model.prototype.fullName = function() {
      var str;
      str = this.get("firstName") + " " + this.get("lastName");
      console.log(str);
      return str;
    };

    return Model;

  })(Backbone.Model);

}).call(this);

},{}],4:[function(require,module,exports){
// Generated by CoffeeScript 1.7.1
(function() {
  var View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = View = (function(_super) {
    __extends(View, _super);

    function View() {
      return View.__super__.constructor.apply(this, arguments);
    }

    View.prototype.tagName = "table";

    View.prototype.template = _.template("<tr>\n  <td>First Name</td>\n  <td>Last Name</td>\n  <td>Age</td>\n</tr>\n<tr>\n  <td class=\"cell first-name\"><%= firstName %></td>\n  <td class=\"cell last-name\"><%= lastName %></td>\n  <td class=\"cell age\"><%= age %></td>\n</tr>");

    View.prototype.events = {
      "click .cell": "displayContents"
    };

    View.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    };

    View.prototype.displayContents = function(evt) {
      return window.displayContents(evt.target);
    };

    return View;

  })(Backbone.View);

}).call(this);

},{}]},{},[1])