// Generated by CoffeeScript 1.7.1
(function() {
  var $, Model, View, body, model, view;

  Model = window.Model;

  View = window.View;

  $ = window.jQuery;

  view = void 0;

  model = void 0;

  body = $("body");

  beforeEach(function() {
    model = new Model({
      firstName: "John",
      lastName: "Doe",
      age: 30
    });
    view = new View({
      model: model
    });
    view.render();
    return body.append(view.$el);
  });

  afterEach(function() {
    return view.remove();
  });

  describe("Model", function() {
    it("Should have a firstName property", function() {
      expect(model.get("firstName")).to.exist;
      return expect(model.get("firstName")).to.equal("John");
    });
    it("Should have a lastName property", function() {
      expect(model.get("lastName")).to.exist;
      return expect(model.get("lastName")).to.equal("Doe");
    });
    it("Should have an age property", function() {
      expect(model.get("age")).to.exist;
      return expect(model.get("age")).to.equal(30);
    });
    return it("Should have a working fullName method", function() {
      var fn;
      expect(model.fullName).to.be.a("function");
      fn = model.fullName();
      return expect(fn).to.equal("John Doe");
    });
  });

  describe("View", function() {
    it("Should have a displayContents method", function() {
      return expect(view.displayContents).to.be.a("function");
    });
    it("Should have rendered correctly", function() {
      var td, tr;
      tr = $("tr");
      td = $("td");
      expect(tr.length).to.equal(2);
      return expect(td.length).to.equal(6);
    });
    return it("Should have working events", function() {
      $(".cell.first-name").click();
      expect(window.lastContent).to.equal("John");
      $(".cell.last-name").click();
      expect(window.lastContent).to.equal("Doe");
      $(".cell.age").click();
      return expect(window.lastContent).to.equal("30");
    });
  });

}).call(this);
