// Generated by CoffeeScript 1.7.1
(function() {
  var View,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  View = (function(_super) {
    __extends(View, _super);

    function View() {
      return View.__super__.constructor.apply(this, arguments);
    }

    View.prototype.tagName = "table";

    View.prototype.template = _.template("<tr>\n  <td>First Name</td>\n  <td>Last Name</td>\n  <td>Age</td>\n</tr>\n<tr>\n  <td class=\"cell first-name\"><%= firstName %></td>\n  <td class=\"cell last-name\"><%= lastName %></td>\n  <td class=\"cell age\"><%= age %></td>\n</tr>");

    View.prototype.events = {
      "click .cell": "displayContents"
    };

    View.prototype.render = function() {
      this.$el.html(this.template(this.model.attributes));
      return this;
    };

    View.prototype.displayContents = function(evt) {
      return window.displayContents(evt.target);
    };

    return View;

  })(Backbone.View);

  if (typeof module !== "undefined" && module !== null ? module.exports : void 0) {
    module.exports = View;
  } else {
    window.View = View;
  }

}).call(this);
